### ISSUE TITLE
Output the per SNP summary statistics?

### ISSUE THREAD

**Issue by mikelove** [mancusolab/twas_sim#1]
This looks great. Thanks for posting!

Could you also output the per SNP summary statistics, e.g. the per SNP GWAS statistics and eQTL statistics?

**Comment by quattro** [comment]
Thanks Mike. Great suggestion. That should be a straightforward addition.

**Comment by mikelove** [comment]
This is great! We’ll be using it this week 😄

**Comment by quattro** [comment]
Cool! Definitely let me know if you have any other suggestions.
