### ISSUE TITLE
Setting random seed

### ISSUE THREAD

**Issue by mikelove** [mancusolab/twas_sim#3]
Mostly for `sim.py` but also for `sample_genes.py` it would be great if it were possible to set `random.seed` for these scripts from a command line argument for computational reproducibility.

Thanks again for putting this online, it seems just right for us.

**Comment by mikelove** [comment]
This what i've added on my end, but it's not really perfect, I think you'd want to not set seed if it's not specified by argument:

#4

**Comment by quattro** [comment]
I'll go ahead and repeat this for sample_genes and push shortly.
