### ISSUE TITLE
Trait-only effects

### ISSUE THREAD

**Issue by mikelove** [mancusolab/twas_sim#8]
hi Nicolas,

As you know, we used `twas_sim` in our [MRLocus](https://doi.org/10.1101/2020.08.14.250720) preprint, which was very helpful, thanks again for your help in adapting the output.

We now want to add additional null simulations that include trait-only effects. The current null simulations we ran involved setting `--var-explained 0` but then the trait will not have significant SNPs, so this is kind of an easy null for methods to deal with.

Suppose I have run `twas_sim` giving me gene 1 and trait 1. I was considering to just re-run `twas_sim` on the same locus to generate gene 2 and trait 2, and then produce trait-associated SNPs this way, which would not be mediated through gene 1. So comparing gene 1 and trait 2 should give me such a null scenario. Just wanted to check your thoughts on this.

Another (separate) simulation I am considering to perform is gene 1 and gene 2 both contributing to the same trait. My thoughts on accomplishing this with the current code base would be to sum trait 1 and trait 2 to make trait 3.

**Comment by quattro** [comment]
Hi @mikelove , glad to hear `twas_sim` has been helpful--I'm happy to extend its capabilities to include direct effects. Your current work-around for multiple genes affecting the same trait should be fine. 

Based off your descriptions, I think a nice path forward would be to refactor the simulator to take some combinator over simulation modules. Each module could represent direct effects on trait, or gene effects on trait. The combinator could then apply them in series, keeping track of intermediate phenotypes (if they exist), and a final trait. Might be overkill, but could be fun and easily extendible for future ideas.

**Comment by mikelove** [comment]
> Your current work-around for multiple genes affecting the same trait should be fine.

Good to hear, just wanted to run this idea by you.

We will be using the current code base for the MRLocus revision with the approach above, but I'd be happy to test out the combinator idea or any others in the future.

Thanks again!

**Comment by quattro** [comment]
Hi @mikelove , the latest code should support this feature under the `--indep-gwas` flag alongside the use of `--h2g-gwas`. Let us know if you have any questions.

**Comment by mikelove** [comment]
Great! This should be super useful. I’ll try it out next time we’re simulating.
